apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: sign-content 
spec:
  steps:
    - name: list-container-contents 
      image: registry.access.redhat.com/ubi9/ubi-micro@sha256:3313e52bb1aad4017a0c35f9f2ae35cf8526eeeb83f6ecbec449ba9c5cb9cb07
      script: |
        echo "MICRO UBI, here : "
        ls -l /workspace/

